// This file was generated by [ts-rs](https://github.com/Aleph-Alpha/ts-rs). Do not edit this file manually.

/**
 * 应用配置，与 Python 端 AppConfig 共享同一份 config.yaml。
 *
 * `roll` → `pitch` 重命名兼容：serde 同时接受 `roll_threshold` / `neutral_roll` 和
 * `pitch_threshold` / `neutral_pitch`，序列化始终使用 `pitch` 系列。
 */
export type AppConfig = { yaw_threshold: number, pitch_threshold: number, yaw_hysteresis: number, pitch_hysteresis: number, neutral_yaw: number, neutral_pitch: number, camera_index: number, language: string, sound_enabled: boolean, autostart_enabled: boolean, snooze_until_iso: string | null, off_axis_streak_threshold_seconds: number, off_axis_repeat_interval_seconds: number, facing_threshold_seconds: number, eyest_threshold_seconds: number, };
